### PR TITLE
[lab-tableau] rute correia

### PR DESCRIPTION
**Pull request by aariops**
better rush this one before the trial runs out

this is done

### CODE REVIEW

**Comment by ta-data-lis** [comment]
Good plan! 

Although for some reason we cannot see the Tableau link, maybe it's something about the privacy settings... ? 

Did you upload/save it to Tableau Public?

**Comment by aariops** [comment]
Not quite sure why it's not working. Here it is again:

https://eu-west-1a.online.tableau.com/t/testingih/views/languagesbyappgenrewuserrating/DiversityinApps?:origin=card_share_link&:embed=n

**Comment by ta-data-lis** [comment]
Hey Rute!

Unfortunately on Tableau Online we cannot access your workbook if you do not give us the permission (Go Linux!!!!!). To make it easier, please download your entire workbook ad PDF, save the file here, and push the repository again, so we can check the final outcome anyway.
Thanks

**Comment by ta-data-lis** [comment]
Lab checked, good job!

Interesting investigation topic. Perhaps, in the pair of charts at the bottom it would have been more effective "visually" to have the mean of languages available in the top bar plot and the rating count as colour scale, all in all well done!

Keep up the good work!

**Pull request closed without merging**
